/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-10-26 14:03:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Application_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script>\n");
      out.write("  function checkDrug() \n");
      out.write("  {\n");
      out.write("\t    if (document.getElementById('yes').checked)\n");
      out.write("\t    {\n");
      out.write("\t      \tdocument.getElementById('druguse').value = '';\n");
      out.write("\t    \tdocument.getElementById('drugusecheck').style.visibility = 'visible';\n");
      out.write("\t    }\n");
      out.write("\t    \n");
      out.write("\t    else if (document.getElementById('no').checked) {\n");
      out.write("\t    \tdocument.getElementById('druguse').value = 'no';\n");
      out.write("\t    \tdocument.getElementById('drugusecheck').style.visiblity = 'visible';\n");
      out.write("\t    }\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("\n");
      out.write("\tfunction checkResume() {\n");
      out.write("\t\talert(\"Please press ok to view your resume\");\n");
      out.write("\t\tdocument.getElementById('action').value = 'resume';\n");
      out.write("\t}\n");
      out.write("\tfunction checkApply() {\n");
      out.write("\t\talert(\"You will not be able to make changes once you submit\");\n");
      out.write("\t\tdocument.getElementById('action').value = 'apply';\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\t    \n");
      out.write("\t    <style>\n");
      out.write("\t    form {\n");
      out.write("\t    padding: 12px 20px;\n");
      out.write("\t     width: 90%;\n");
      out.write("\n");
      out.write("  padding : 5px;\n");
      out.write("     margin: 8px 0;\n");
      out.write("  \n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=text] {\n");
      out.write("    width: 90%;\n");
      out.write("    padding: 12px 20px;\n");
      out.write("    margin: 8px 0;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    background-image: url('searchicon.png');\n");
      out.write("}\n");
      out.write("input[type=text]:focus {\n");
      out.write("    background-color: #7bc475;\n");
      out.write("}\n");
      out.write("\t    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<br><br><br><br>\n");
      out.write("\n");
      out.write(" <form   action =\"ApplicationServlet\" method =\"post\">\n");
      out.write(" \n");
      out.write(" \n");
      out.write("  <div class=\"form-group\">\n");
      out.write("  Name*: <input type=\"text\" class=\"form-control\" id=\"fullname\" name=\"fullname\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("   <div class=\"form-group\">\n");
      out.write("  Email*: <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("   <div class=\"form-group\">\n");
      out.write("   Birthday*:<input type=\"text\" class=\"form-control\" id=\"birthday\" name=\"birthday\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("   <div class=\"form-group\">\n");
      out.write("    <label for=\"address\">Address*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("  <label for=\"education\">Education*:</label>\n");
      out.write("  <input type=\"text\" class=\"form-control\" id=\"education\" name=\"education\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("     <div class=\"form-group\">\n");
      out.write("    <label for=\"jobhistory\">Job history*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"jobhistory\" name=\"jobhistory\">\n");
      out.write("  </div>\n");
      out.write("\t  \n");
      out.write("\t   <div class=\"form-group\">\n");
      out.write("    <label for=\"summary\">Summary*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"summary\" name=\"summary\">\n");
      out.write("  </div>\n");
      out.write("\t  \n");
      out.write("\t    <div class=\"form-group\">\n");
      out.write("    <label for=\"objective\">Objective*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"objective\" name=\"objective\">\n");
      out.write("  </div>\n");
      out.write("\t   \n");
      out.write("\t      <div class=\"form-group\">\n");
      out.write("    <label for=\"skill\">Skills*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"skills\" name=\"skills\">\n");
      out.write("  </div>\n");
      out.write("\t   \n");
      out.write("\t   \n");
      out.write("\t  \n");
      out.write("     <div class=\"form-group\">\n");
      out.write("    <label for=\"references\">References*:</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"references\" name=\"references\">\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("    <label for=\"druguse\">Drug Use:</label>\n");
      out.write("    Yes <input type=\"radio\" onclick=\"javascript:checkDrug();\" name=\"check\" id=\"yes\" value=\"yes\"/>\n");
      out.write("     No<input type=\"radio\" onclick=\"javascript:checkDrug();\" name=\"check\" id=\"no\" value=\"no\"/>\t\t\t      \n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div id=\"drugusecheck\" class=\"form-group\" style=\"visibility: hidden\">\n");
      out.write("   Type of drug   <input type=\"text\" class=\"form-control\" id=\"druguse\" name=\"druguse\" value= \"\">\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"veteran\">Veteran*:</label> \n");
      out.write(" \t Yes <input type=\"radio\"  name=\"veteran\" id=\"yes\" value=\"yes\"/>\n");
      out.write("     No<input type=\"radio\"  name=\"veteran\" id=\"no\" value=\"no\"/>\t\t\t    \n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label for=\"citizenship\">Citizenship*:</label> \n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"citizenship\" name=\"citizenship\">\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("\t <input type=\"submit\" onclick=\"javascript:checkResume();\"  id=\"resume\" value=\"Export as Resume\"/>\n");
      out.write("\t <input type=\"hidden\" name=\"action\" id=\"action\" value=\"\">\n");
      out.write("\t \n");
      out.write("\t <input type=\"submit\" onclick=\"javascript:checkApply();\"  id=\"apply\" value=\"Apply to the job\"/>\n");
      out.write("\t \n");
      out.write("</center>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
